### ISSUE TITLE
version number for v0.2.2

### ISSUE THREAD

**Issue by romaingroux** [smithlabcode/falco#11]
Nothing serious... 
In the source code of your v0.2.2 release it seems you forgot to change the value of FALCO_VERSION at line 303 of src/falco.cpp. It is still  "falco v0.2.1" so it prints 'v0.2.1' when you run 'falco -v', instead of 'v0.2.2'.

**Comment by guilhermesena1** [comment]
Hello,

Thank you so much for reporting this issue! It turns out the version number was also not appearing correctly in the html report. I slightly restructured the code to avoid this error in the future. Commit 5cf58e289ad070419178b3b4a29dad7c0aa6fbb9 should fix this, and I'll make sure this remains correct in the next release.
