### ISSUE TITLE
Package adapters and other default files with bioconda

### ISSUE THREAD

**Issue by schorlton** [smithlabcode/falco#31]
Hi, thanks for the great tool!

Is it still the case that the [adapter_list.txt](https://github.com/smithlabcode/falco/blob/master/Configuration/adapter_list.txt) and potentially the other [default configuration files](https://github.com/smithlabcode/falco/tree/master/Configuration) are not shipped with the bioconda package? 
https://github.com/smithlabcode/falco/issues/16 and https://github.com/smithlabcode/falco/releases/tag/v0.3.0

I could not find them when I tried a simple `find`. Is there a reason for this? If not, perhaps they should be shipped with bioconda and `falco` should default to using them, similar to how FastQC functions? Thanks for your consideration!

**Comment by guilhermesena1** [comment]
Hey.

Thank you for reaching out about this. The fix I found for this problem was not really a fix. What we did is to have the default information of the files built into the program and ship it to conda without them. We will be drafting a new release in the coming weeks given the recent issues that arose, and I will tyr to find the proper syntax in autotools so the program knows where it is installed on Conda and knows the absolute path for these files at compile time.

In the meantime, the **super dirty** solution would be as follows:

(1) under the `bin` directory on conda, rename `falco` to `falco-tmp`
(2) place your default adapters anywhere on conda
(3) under the conda `bin` directory, create a file called `falco` with the following:
```
/path/to/conda/bin/falco-tmp -c /path/to/your/contaminant_list.txt -l /path/to/your/limits.txt -a /path/to/your/adapter_list.txt $*; 
```

now you can run `falco any-file.fastq` and add any other user flags you might need :)

Again I'm sorry for proposing this trick, it shouldn't be on the user to have to sort these things out. We'll find a more elegant solution on the next release.

**Comment by schorlton** [comment]
Thanks for your response! I think I'll wait for the next release so I can use falco as a drop-in replacement for FastQC...thanks!

**Comment by guilhermesena1** [comment]
Better (very) late than never, I just created a falco-1.2.0 release, and when updating Conda I replicated FastQC's approach of adding the default files to `opt/falco-1.2.0/Configuration`, so now you can use them as a template to run falco :)

**Comment by schorlton** [comment]
Thank you!! :tada:
