### ISSUE TITLE
Adapter content plot shows wrong read lengths

### ISSUE THREAD

**Issue by shigita** [smithlabcode/falco#37]
In the version 1.0.0, the plot shows read length of 489 bp, even though the actual length is 100 bp.

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/40628880/188115041-3a392f0c-594f-46ad-9d86-278699fa2800.png">

The command, fastq file, and adapter list to reproduce this issue are as follows:
```
falco -a qc_adaptors_list.txt example.fq.gz
```
[qc_adaptors_list.txt](https://github.com/smithlabcode/falco/files/9476400/qc_adaptors_list.txt)
[example.fq.gz](https://github.com/smithlabcode/falco/files/9476477/example.fq.gz)

**Comment by andrewdavidsmith** [comment]
@shigita This should be fixed in commit 78eac8d44b67c04005542855d70aafe1879a608c and I'm able to get the image with the range to 100 bp using your files and command (thanks for those!!). Be aware: adaptor enrichment can only be calculated up to 91 positions, if the smallest adapter is 10bp and the read length is 100, but the most recent commit plots all the way to 100, instead of 91, which is reasonable since the plot is cumulative. I'm closing the issue, but happy to reopen if needed.
